ines:
  name: ines-myproject-dev
  host: ines.dev.mi.fr
  secretValue: |-
    ##
          data:
              ca.crt: XXX
              tls.crt: XXX
              tls.key: XXX
    sops:
      kms: []
      gcp_kms: []
      azure_kv: []
      hc_vault: []
      age:
          - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
            enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ0dHMGZhb3VLZjJNbWhO
                L2J6ckJ1R2tnanF3WFJhQTdMRGswNlY1SXhNCm95NXRJbTVma3BUQlkvdHMxK05p
                cUlmbnpoUElKRWQ1eEhJY0txcjlRQW8KLS0tIFFVMThLcnBRdkQ2R2t2R1Exc3ZZ
                dXpvYUJoUVRaMERHR0tSRlpmUk43MTAKW0qyKrlp8xkPsI+nGP/DG8fJLePXiBD0
                goPbZXOVttHZPol2lK6mAyDOKUBN4H7rSuWeOflm7Vxe48aEExLQCw==
                -----END AGE ENCRYPTED FILE-----
      lastmodified: "2023-10-12T12:52:57Z"
      mac: ENC[AES256_GCM,data:7n9r/cyek54BvFYAQumq6Hx0IQzeF/e84cshP1Vg6jnXWb4W+9SzG0HsuwB2JJBj19R88cMYi5ESUpD4GgVjnRV84uXw394jL/Z/iH6Ddk3+RDeh9VeQZwmbFYjAeMWNyLFT44ci9el4HrN0jFq39wuABUQ8tYqZI+qu7K0At64=,iv:xO6hTvpx5mNNXP/HBTjq9KOAecQTlUgUOCjbSxuZM9o=,tag:hDl+SFvY3ZqrWY7aXnDhHA==,type:str]
      pgp: []
      encrypted_regex: (crt|key)
      version: 3.7.3
